import { existsSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { join, resolve, extname } from 'node:path';

type ProjectType = 'typescript' | 'python' | 'rust' | 'java' | 'go' | 'unknown';

export interface ProjectAnalysis {
  type: ProjectType;
  rootDir: string;
  fileCount: number;
  languages: string[];
  hasTests: boolean;
  hasGit: boolean;
}

const LANG_EXT: Record<string, string> = {
  '.ts': 'TypeScript', '.tsx': 'TypeScript', '.js': 'JavaScript', '.jsx': 'JavaScript',
  '.py': 'Python', '.rs': 'Rust', '.go': 'Go', '.java': 'Java',
  '.cpp': 'C++', '.c': 'C', '.rb': 'Ruby',
};

const SKIP = new Set(['node_modules', 'dist', 'build', '.git', '.coderelay', 'target', '__pycache__', '.venv']);

export function analyzeProject(dir: string): ProjectAnalysis {
  const type = detectProjectType(dir);
  const langCounts: Record<string, number> = {};
  let fileCount = 0;
  let hasTests = false;

  function walk(current: string, depth: number): void {
    if (depth > 5) return;
    let entries: string[];
    try { entries = readdirSync(current) as string[]; } catch { return; }
    for (const name of entries) {
      if (SKIP.has(name) || name.startsWith('.')) continue;
      const full = join(current, name);
      let st: ReturnType<typeof statSync>;
      try { st = statSync(full); } catch { continue; }
      if (st.isDirectory()) { walk(full, depth + 1); continue; }
      fileCount++;
      const lang = LANG_EXT[extname(name).toLowerCase()];
      if (lang) langCounts[lang] = (langCounts[lang] ?? 0) + 1;
      const lower = name.toLowerCase();
      if (lower.includes('test') || lower.includes('spec') || lower.includes('.test.') || lower.includes('.spec.')) hasTests = true;
    }
  }

  walk(dir, 0);

  const languages = Object.entries(langCounts)
    .sort((a, b) => b[1] - a[1])
    .map(([lang]) => lang);

  return {
    type,
    rootDir: dir,
    fileCount,
    languages,
    hasTests,
    hasGit: existsSync(join(dir, '.git')),
  };
}

function detectProjectType(dir: string): ProjectType {
  if (existsSync(join(dir, 'tsconfig.json')) || existsSync(join(dir, 'package.json'))) return 'typescript';
  if (existsSync(join(dir, 'Cargo.toml'))) return 'rust';
  if (existsSync(join(dir, 'go.mod'))) return 'go';
  if (existsSync(join(dir, 'pom.xml')) || existsSync(join(dir, 'build.gradle'))) return 'java';
  if (existsSync(join(dir, 'pyproject.toml')) || existsSync(join(dir, 'requirements.txt'))) return 'python';
  return 'unknown';
}

const TYPE_CHECKER: Record<ProjectType, string> = {
  typescript: 'npx tsc --noEmit',
  python: 'npx pyright',
  rust: 'cargo check',
  java: 'mvn compile -q',
  go: 'go build ./...',
  unknown: '',
};

function buildConfig(analysis: ProjectAnalysis): string {
  const { type } = analysis;
  return `# coderelay.yaml — generated by \`coderelay init\`
version: 1

project:
  type: ${type}
  rootDir: .

router:
  defaultProvider: ollama
  providers:
    ollama:
      baseUrl: http://localhost:11434
      model: qwen2.5-coder:7b
    anthropic:
      model: claude-sonnet-4-6
      # apiKey: set ANTHROPIC_API_KEY env var
    openai:
      model: gpt-4o-mini
      # apiKey: set OPENAI_API_KEY env var
    openrouter:
      model: anthropic/claude-sonnet-4-6
      # apiKey: set OPENROUTER_API_KEY env var

routing:
  embed: ollama
  summarize: ollama
  classify: ollama
  sanitize: ollama
  plan: anthropic
  code-gen: anthropic

indexer:
  dbPath: .coderelay/graph.db
  lanceDbPath: .coderelay/lance

memory:
  sessionDb: .coderelay/session.db
  longTermDb: .coderelay/longterm.db

mcp:
  enabled: true
  transport: stdio

governor:
  allowedPaths:
    - .
  sandbox: worktree
${TYPE_CHECKER[type] ? `  typeChecker: "${TYPE_CHECKER[type]}"` : ''}

agents:
  default: claude
  timeoutMs: 300000
`;
}

export interface InitOptions {
  dir?: string | undefined;
  force?: boolean | undefined;
  quiet?: boolean | undefined;
}

export function runInit(opts: InitOptions = {}): void {
  const dir = resolve(opts.dir ?? process.cwd());
  const outPath = join(dir, 'coderelay.yaml');
  const dbDir = join(dir, '.coderelay');
  const quiet = opts.quiet === true;

  if (existsSync(outPath) && opts.force !== true) {
    console.error(`coderelay.yaml already exists. Use --force to overwrite.`);
    process.exit(1);
  }

  // Phase 1 — Project analysis
  if (!quiet) console.log('\nPhase 1/4  Analysing project...');
  const analysis = analyzeProject(dir);
  if (!quiet) {
    console.log(`  Type      : ${analysis.type}`);
    console.log(`  Files     : ${analysis.fileCount}`);
    console.log(`  Languages : ${analysis.languages.join(', ') || 'unknown'}`);
    console.log(`  Tests     : ${analysis.hasTests ? 'found' : 'none detected'}`);
    console.log(`  Git       : ${analysis.hasGit ? 'yes' : 'no'}`);
  }

  // Phase 2 — Memory & DB directory init
  if (!quiet) console.log('\nPhase 2/4  Initialising database directories...');
  mkdirSync(dbDir, { recursive: true });
  if (!quiet) console.log(`  Created   : ${dbDir}/`);

  // Phase 3 — Write config
  if (!quiet) console.log('\nPhase 3/4  Writing coderelay.yaml...');
  const config = buildConfig(analysis);
  writeFileSync(outPath, config, 'utf8');
  if (!quiet) console.log(`  Config    : ${outPath}`);

  // Phase 4 — Next steps
  if (!quiet) {
    console.log('\nPhase 4/4  Setup complete.\n');
    console.log('Next steps:');
    console.log('  1. coderelay index .          # index this repo');
    console.log('  2. coderelay run "your task"  # run a task');
    if (!analysis.hasGit) console.log('\n  Warning: no .git directory detected. Worktree sandbox requires git.');
    console.log();
  }
}
